name: Testing
on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    test:
        name: integration tests
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - uses: oven-sh/setup-bun@v1

            - name: Install dependencies
              run: cd api && bun install

            - name: Setup database
              run: cd api && bun run pretest

            - name: Start service
              run: cd api && nohup bun src/index.ts &

            - name: Run tests
              run: cd api && bun run test --filter=@memd/api